### PR TITLE
easily load environment vars

### PR DESCRIPTION
**Pull request by matgar1997**
makes it easier to load and edit environment variables into the project,

This PR will require to reinstall requirements.txt

### CODE REVIEW

**Comment by AlbMej** [comment]
We can share the file in slack or something. We shouldn't release any credentials.

**Comment by AlbMej** [comment]
The environment variables are loaded in via the settings file using Python Decouple. Any reasons why we should switch?

**Comment by matgar1997** [comment]
may want a file in root .env with contents
SECRET_KEY=!eep#0++x*bvn&x49+31t@_=09j#+-49q)wafyym&9_nhrzaks
SDDTF_USER=sdNd
SDDTF_PASS=mongo123
STATUS_VAR=dev

**Comment by AlbMej** [comment]
We shouldn't post any credentials. The current setup works with .env in the root.

**Comment by matgar1997** [comment]
what does it do

**Comment by matgar1997** [comment]
granted, I posted it here so the group could see. but .env was in the gitignore

**Comment by AlbMej** [comment]
Here's the repo https://github.com/henriquebastos/python-decouple

It's in the gitignore to avoid the accidental committal of credentials.

**Pull request closed without merging**
