### PR TITLE
Tutor search backend

### LINKED ISSUE #7: Tutor Search Backend

### PR DESCRIPTION
**Pull request by johnwparent**

### CODE REVIEW

**Comment by matgar1997** [comment]
I am running into issues with testing this. probably because of conflicts with the database/migrations. But I am getting a server 500 error when I search a class that doesn't exist in the database

**Review by matgar1997 — CHANGES_REQUESTED** [review]
After doing a fresh clone, the tutor search causes a server 500 error

**Comment by johnwparent** [comment]
Fixed 500 error, after fresh clone and run, works fine

**Review by matgar1997 — APPROVED** [review]
Looks great!

**Pull request merged**
